baseURL = "https://nataprawiraf.me/"
title = "nata"
googleAnalytics = "UA-123-456-789"
theme = "github-style"
copyright = "© 2020. nata. theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"
pygmentsUseClasses = true

[params]
  author = "nata"
  description = "hello, my name is nata, welcome to my website"
  github = "natkingchloe"
  twitter = "natyourbae"
  email = "nataprawiraf@gmail.com"
  avatar = "https://avatars3.githubusercontent.com/u/21014596?s=460&u=76896d102e290321e7266bbdfdb474b64cf09715&v=4"
  url = "https://nataprawiraf.me"
