baseURL: "https://n0irx.fun"
title: n0irx.fun
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    profileMode:
        enabled: true
        title: "n0irx.fun" # optional default will be site title
        subtitle: "personal site by Nata"
        # imageUrl: "<image link>" # optional
        # imageTitle: "<title of image as alt>" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        buttons:
            - name: posts
              url: "/posts"
            - name: tags
              url: "/tags"
            - name: resume
              url: "/resume"

    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "n0irx's Personal Site"
    description: "n0irx's Personal Site"
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: true
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/images/favico.png"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /images/favico.png
        iconHeight: 35

    # profile-mode
    # profileMode:
    #     enabled: false # needs to be explicitly set
    #     title: ExampleSite
    #     subtitle: "This is subtitle"
    #     imageUrl: "<img location>"
    #     imageWidth: 120
    #     imageHeight: 120
    #     imageTitle: my image
    #     buttons:
    #         - name: Posts
    #           url: posts
    #         - name: Tags
    #           url: tags

    # home-info mode
    # homeInfoParams:
    #     Title: "Hi there \U0001F44B"
    #     Content: Welcome to personal website

    socialIcons:
        - name: github
          url: "https://github.com/n0irx"
        - name: gitlab
          url: "https://gitlab.com/n0irx"
        - name: linkedin
          url: "https://linkedin.com/in/nataprawiraf"
        - name: email
          url: "mailto:nataprawiraf@gmail.com"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main: 
        - identifier: posts
          name: posts
          url: /posts/
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: resume
          name: resume
          url: /resume/

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai